//____________________________________________________________________________________
void notFound(AsyncWebServerRequest *request) {

  String html = "<!DOCTYPE html><head>";
  html += "<meta charset='UTF-8'>";
  html += "<title> EcoHaven | Sintrud </title>";
  html += "<link rel='stylesheet' href='style.css'>";
  html += "<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>";
  html += "<meta name='viewport' content='width=device-width, initial-scale=1.0'>";
  html += "</head>";
  html += "<body>";
  html += "<div class='sidebar close'>";
  html += "<div class='logo-details'>";
  html += "<i class='bx bxl-mongodb'></i>";
  html += "<span class='logo_name'>EcoHaven</span>";
  html += "</div>";
  html += "<ul class='nav-links'>";
  html += "<li>";
  html += "<a href='/'>";
  html += "<i class='bx bx-home-alt-2'></i>";
  html += "<span class='link_name'>Inicio</span>";
  html += "</a>";
  html += "<ul class='sub-menu blank'>";
  html += "<li><a class='link_name' href='/'>Inicio</a></li>";
  html += "</ul>";
  html += "</li>";
  html += "<li>";
  html += "</li>";
  html += "</ul>";
  html += "</div>";
  html += "<section class='home-section'>";
  html += "<div class='home-content'>";
  html += "<i class='bx bx-menu'></i>";
  html += "</div>";
  html += "<header>";
  //<!-- Aquí puedes colocar tu encabezado de página, logotipo, menú de navegación, etc. -->
  html += "</header>";
  html += "<main>";
  html += "<div class='cuerpo'>";
  html += "<div class='error404'>";
  html += "<h1>404</h1>";
  html += "<div class='cloak__wrapper'>";
  html += "<div class='cloak__container'>";
  html += "<div class='cloak'></div>";
  html += "</div>";
  html += "</div>";
  html += "<div class='info'>";
  html += "</a><h2>We can't find that page</h2>";
  html += "<p>We're fairly sure that page used to be here, but seems to have gone missing. We do apologise onit's behalf.</p>";
  html += "<a href='/' rel='noreferrer noopener'>Home</a>";
  html += "</div>";
  html += "<br>";
  html += "<br>";
  html += "<br>";
  html += "<br>";
  html += "</div>";
  html += "</div>";
  html += "</main>";
  //<!-- TABLA -->
  html += "</section>";
  html += "<footer>"; 
  html += "<ul class='social_icon'>";
  html += "<li><a href='#' target='_blank'><i class='bx bxl-instagram'></i></a></li>";
  html += "<li><a href='#' target='_blank'><i class='bx bxl-facebook'></i></a></li>";
  html += "<li><a href='https://github.com/AlessandroKlein' target='_blank'><i class='bx bxl-github'></i></a></li>";
  html += "<li><a href='#'><i class='bx bxl-telegram' target='_blank'></i></a></li>";
  html += "<li><a href='#'><i class='bx bxl-discord-alt' target='_blank'></i></a></li>";
  html += "<li><a href='https://www.youtube.com/channel/UCEv8bj0D22b9hCfhylVzmoQ'><i class='bx bxl-youtube' target='_blank'></i></a></li>";
  html += "</ul>";
  html += "<ul class='menu__footer'>";
  html += "<li><a href='/'>Inicio</a></li>";
  html += "<li><a href='#'>Config</a></li>";
  html += "</ul>";
  html += "<div class='p-class'>";
  html += "<p id='copyright'>&copy; AKV. Todos los derechos reservados.</p>";
  html += "<div class='job'>Version: " + String(VERSION) + "</div>";
  html += "</div>";
  html += "</footer>";
  html += "<script type='module' src='https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js'></script>";
  html += "<script nomodule src='https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js'></script>";
  html += "<script>";
  html += "let arrow = document.querySelectorAll('.arrow');for (var i = 0; i < arrow.length; i++) {arrow[i].addEventListener('click', (e) => {let arrowParent = e.target.parentElement.parentElement;arrowParent.classList.toggle('showMenu');});}";
  html += "let sidebar = document.querySelector('.sidebar');let sidebarBtn = document.querySelector('.bx-menu');console.log(sidebarBtn);sidebarBtn.addEventListener('click', () => {sidebar.classList.toggle('close');});";
  html += "document.addEventListener('DOMContentLoaded', function () {var currentYear = new Date().getFullYear();var copyright = document.getElementById('copyright');copyright.innerHTML = '&copy;' + currentYear + ' Sintrud. Todos los derechos reservados.';});";
  html += "</script>";
  html += "</body></html>";

  //request->send(404, "text/plain", "Not found");
  request->send(404, "text/html", html);
}